name: docker-edge-computing

services:
    node-red:
        container_name: NodeRED
        build: ./node-red
        restart: always
        ports:
            - ${NODE_RED_PORT}:1880
        volumes:
            - node-red-data:/data
            - node-red-pallets:/data/node_modules
        networks:
            - data-processing-network
    
    grafana:
        container_name: Grafana
        build: ./grafana
        restart: always
        depends_on:
            - node-red
            - influxdb
        ports:
            - ${GRAFANA_PORT}:3000
        volumes:
            - grafana-data:/var/lib/grafana
            - /var/lib/grafana/plugins
        networks:
            - data-processing-network
    
    influxdb:
        container_name: InfluxDB
        image: influxdb:2.6.1
        restart: always
        ports:
            - ${INFLUXDB_PORT}:8086
        volumes:
            - influxdb-data:/var/lib/influxdb2
        networks:
            - data-processing-network

    http-server:
        container_name: WebServer
        build: ./httpd
        restart: always
        ports:
            - ${HTTPD_PORT}:80
        volumes:
            - www-files:/usr/local/apache2/htdocs
        networks:
            - docker-network

    ftp-server:
        container_name: FileServer
        build: ./pure-ftpd
        restart: always
        ports:
            - ${PURE_FTPD_DATA_PORT}:20
            - ${PURE_FTPD_CONTROL_PORT}:21
            - "${PURE_FTPD_MIN_PASV_PORT}-${PURE_FTPD_MAX_PASV_PORT}:\
               ${PURE_FTPD_MIN_PASV_PORT}-${PURE_FTPD_MAX_PASV_PORT}"
        volumes:
            - pure-ftpd-data:/etc/pureftpd
            - www-files:/ftp/www
        environment:
            - PUBLIC_HOST=${PURE_FTPD_PUBLIC_HOST}
            - MIN_PASV_PORT=${PURE_FTPD_MIN_PASV_PORT}
            - MAX_PASV_PORT=${PURE_FTPD_MAX_PASV_PORT}
        networks:
            - docker-network
    
    dns-server:
        container_name: NameServer
        build: ./bind9
        restart: always
        environment:
            - BIND9_USER=root
            - TZ=America/Sao_Paulo
        ports:
            - 53:53/tcp
            - 53:53/udp
        volumes:
            - dns-config-data:/etc/bind
            - dns-cache-data:/var/cache/bind

volumes:
    node-red-data:
        name: NodeREDData
    node-red-pallets:
        name: NodeREDPallets
    grafana-data:
        name: GrafanaData
    influxdb-data:
        name: InfluxDBData
    pure-ftpd-data:
        name: PureFTPdData
    www-files:
        name: WebFiles
    dns-config-data:
        name: DNSConfigData
    dns-cache-data:
        name: DNSCacheData

networks:
    docker-network:
        name: DockerNetwork
        driver: bridge
    data-processing-network:
        name: DataProcessingNetwork
        driver: bridge
