version: '3.7'

services:
    node-red:
        container_name: NodeRED
        build: ./node-red
        ports:
            - 2880:1880
        volumes:
            - ./node-red/data:/data
            - /data/node_modules
        networks:
            - docker-network
    
    grafana:
        container_name: Grafana
        build: ./grafana
        depends_on:
            - node-red
        ports:
            - 3330:3000
        volumes:
            - grafana-data:/var/lib/grafana
            - /var/lib/grafana/plugins
        networks:
            - docker-network

volumes:
    grafana-data:

networks:
    docker-network:
        name: DockerNetwork
        driver: bridge
