version: '3.7'

name: docker-edge-computing

services:
    node-red:
        container_name: NodeRED
        build: ./node-red
        ports:
            - 2880:1880
        volumes:
            - node-red-data:/data
            - node-red-pallets:/data/node_modules
        networks:
            - docker-network
    
    grafana:
        container_name: Grafana
        build: ./grafana
        depends_on:
            - node-red
            - influxdb
        ports:
            - 3330:3000
        volumes:
            - grafana-data:/var/lib/grafana
            - /var/lib/grafana/plugins
        networks:
            - docker-network
    
    influxdb:
        container_name: InfluxDB
        image: influxdb:2.6.1
        ports:
            - 9096:8086
        volumes:
            - influxdb-data:/var/lib/influxdb2
        networks:
            - docker-network

    http-server:
        container_name: WebServer
        build: ./apache
        ports:
            - 88:80
        volumes:
            - www-files:/usr/local/apache2/htdocs
        networks:
            - docker-network

    ftp-server:
        container_name: FileServer
        build: ./pure-ftpd
        ports:
            - 20:20
            - 21:21
            - 21100-21110:21100-21110
        volumes:
            - pure-ftpd-data:/etc/pureftpd
            - www-files:/ftp/www
        environment:
            - PUBLIC_HOST=192.168.150.200
            - MIN_PASV_PORT=21100
            - MAX_PASV_PORT=21110
        networks:
            - docker-network

volumes:
    node-red-data:
        name: NodeREDData
    node-red-pallets:
        name: NodeREDPallets
    grafana-data:
        name: GrafanaData
    influxdb-data:
        name: InfluxDBData
    pure-ftpd-data:
        name: PureFTPdData
    www-files:
        name: WebFiles

networks:
    docker-network:
        name: DockerNetwork
        driver: bridge
